# Generated by Django 4.2 on 2025-08-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('body', models.CharField(max_length=255, verbose_name='本文')),
                ('tags', models.CharField(max_length=255, verbose_name='タグ')),
                ('updateDate', models.DateTimeField(blank=True, null=True, verbose_name='更新日')),
            ],
            options={
                'db_table': 'memos',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=255, unique=True, verbose_name='タグ名')),
            ],
            options={
                'db_table': 'tags',
            },
        ),
    ]
