# Generated by Django 4.2 on 2025-09-07 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memos',
            name='body',
            field=models.CharField(default='なし', max_length=255, verbose_name='本文'),
        ),
        migrations.RemoveField(
            model_name='memos',
            name='tags',
        ),
        migrations.AlterField(
            model_name='memos',
            name='title',
            field=models.CharField(default='タイトルなし', max_length=100, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='memos',
            name='updateDate',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='更新日'),
        ),
        migrations.AddField(
            model_name='memos',
            name='tags',
            field=models.ManyToManyField(to='memoapp.tags', verbose_name='タグ'),
        ),
    ]
