# Generated by Django 4.2 on 2025-09-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoapp', '0002_alter_memos_body_remove_memos_tags_alter_memos_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memos',
            name='body',
            field=models.TextField(default='なし', max_length=255, verbose_name='本文'),
        ),
    ]
